#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidFloatingActionButtonQs.Resource", IsApplication=true)]

namespace AndroidFloatingActionButtonQs
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int fab_addButtonColorNormal = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int fab_addButtonColorPressed = 2130771976;
			
			// aapt resource value: 0x7f01000b
			public const int fab_addButtonPlusIconColor = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fab_addButtonSize = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public const int fab_addButtonStrokeVisible = 2130771980;
			
			// aapt resource value: 0x7f010002
			public const int fab_colorDisabled = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int fab_colorNormal = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int fab_colorPressed = 2130771969;
			
			// aapt resource value: 0x7f01000f
			public const int fab_expandDirection = 2130771983;
			
			// aapt resource value: 0x7f010004
			public const int fab_icon = 2130771972;
			
			// aapt resource value: 0x7f01000d
			public const int fab_labelStyle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fab_labelsPosition = 2130771982;
			
			// aapt resource value: 0x7f010000
			public const int fab_plusIconColor = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int fab_size = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int fab_stroke_visible = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int fab_title = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int background = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int black_semi_transparent = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int blue_semi_transparent = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int blue_semi_transparent_pressed = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int half_black = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int pink = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int pink_pressed = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int white = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int white_pressed = 2131099652;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int fab_actions_spacing = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fab_icon_size = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fab_labels_margin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fab_plus_icon_size = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int fab_plus_icon_stroke = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int fab_shadow_offset = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int fab_shadow_radius = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int fab_size_mini = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int fab_size_normal = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int fab_stroke_width = 2130968585;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fab_bg_mini = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fab_bg_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fab_label_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_fab_star = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int naxam = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int action_a = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int action_b = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int action_enable = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int button_gone = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int button_remove = 2131034129;
			
			// aapt resource value: 0x7f050006
			public const int down = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int fab_expand_menu_button = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int fab_label = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int left = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int mini = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int multiple_actions = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int multiple_actions_down = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int multiple_actions_left = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int normal = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int normal_plus = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int pink_icon = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int right = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int right_labels = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int semi_transparent = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int setter = 2131034122;
			
			// aapt resource value: 0x7f050015
			public const int setter_drawable = 2131034133;
			
			// aapt resource value: 0x7f050007
			public const int up = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int Theme = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int menu_labels_style = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int theme_textview_style = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AddFloatingActionButton = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int AddFloatingActionButton_fab_plusIconColor = 0;
			
			public static int[] FloatingActionButton = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorDisabled = 1;
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorNormal = 2;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_icon = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_size = 4;
			
			// aapt resource value: 6
			public const int FloatingActionButton_fab_stroke_visible = 6;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_title = 5;
			
			public static int[] FloatingActionsMenu = new int[] {
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int FloatingActionsMenu_fab_addButtonColorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionsMenu_fab_addButtonColorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionsMenu_fab_addButtonPlusIconColor = 3;
			
			// aapt resource value: 2
			public const int FloatingActionsMenu_fab_addButtonSize = 2;
			
			// aapt resource value: 4
			public const int FloatingActionsMenu_fab_addButtonStrokeVisible = 4;
			
			// aapt resource value: 7
			public const int FloatingActionsMenu_fab_expandDirection = 7;
			
			// aapt resource value: 5
			public const int FloatingActionsMenu_fab_labelStyle = 5;
			
			// aapt resource value: 6
			public const int FloatingActionsMenu_fab_labelsPosition = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
